# Generated by Django 5.1.7 on 2025-05-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='facebook_link',
            field=models.CharField(blank=True, default='www.facebook.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='tiktok_link',
            field=models.CharField(blank=True, default='www.tiktok.com', max_length=255, null=True),
        ),
    ]
