# Generated by Django 5.1.7 on 2025-05-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_config_facebook_link_config_tiktok_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='contact_phone',
            field=models.CharField(blank=True, default='+38162227054\u2028', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='email',
            field=models.EmailField(blank=True, default='contact@miyamie.com', max_length=254, null=True),
        ),
    ]
