# Generated by Django 5.1.7 on 2025-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_config_contact_phone_alter_config_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='slug',
            field=models.SlugField(default='ses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='contact_phone',
            field=models.CharField(blank=True, default='+38162227054', max_length=100, null=True),
        ),
    ]
