# Generated by Django 5.1.7 on 2025-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_dress_slug_alter_config_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='home_page',
            field=models.IntegerField(default=0),
        ),
    ]
