# Generated by Django 5.1.7 on 2025-06-25 16:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_dress_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='delivery_info',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Delivery information', verbose_name='Sadržaj'),
        ),
    ]
