# Generated by Django 5.1.7 on 2025-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_config_delivery_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='size',
            field=models.CharField(choices=[('standard', 'Standard'), ('xl', 'XL')], default='standard', max_length=20),
        ),
    ]
