# Generated by Django 5.1.7 on 2025-06-30 12:40

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_dress_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='delivery_info_en',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Delivery information', verbose_name='Content (en)'),
        ),
        migrations.AlterField(
            model_name='dress',
            name='tag',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('bestseller', 'Bestseller'), ('sale', 'Sale'), ('for_sale', 'For Sale'), ('rent', 'Rent')], max_length=20, null=True),
        ),
    ]
